### ISSUE TITLE
Hello from DDPS

### ISSUE THREAD

**Issue by Zeqiang-Lai** [shinying/dmp#1]
hello dmp team

congrat for the great work.

would you mind to cite our work DDPS which also discuss the generative diffusion prior for segmentation for your next version if possible？

Denoising Diffusion Semantic Segmentation with Mask Prior Modeling

https://arxiv.org/abs/2306.01721

**Comment by shinying** [comment]
Thanks for your interest in our work. We will carefully read the paper and consider your suggestion.
