### ISSUE TITLE
About the performance of depth

### ISSUE THREAD

**Issue by jingheya** [shinying/dmp#4]
Thanks for sharing this outstanding work!

I notices that you released a new weight for depth prediction without prompts. The new weight was trained on hypersim dataset which is also utilized in Marigold. Have you conducted a comparison of the metrics of your method with Marigold on this Hypersim dataset?

**Comment by jingheya** [comment]
By the way, could you provide the visualization code for depth to translate the .npy file to image, such as below: 
<img width="316" alt="image" src="https://github.com/shinying/dmp/assets/57147752/044dee3b-44d9-4a9e-95c7-58e52ea7384c">
Thanks in advance!

**Comment by shinying** [comment]
Thanks for your interest. 

Please refer to Appendix B.3 for the performance of the model trained with Hypersim.

To visualize depths, you may first normalize the depth values to be in [0, 1] and use the function [here](https://github.com/shinying/dmp/blob/17fdd6a60d26b05db9df658dfeee8f3312cf0f86/app.py#L33) to colorize an np.array.

**Comment by jingheya** [comment]
Thank you very much! This is very helpful.
