### ISSUE TITLE
About LoRA Rank

### ISSUE THREAD

**Issue by LIU-Yuxin** [shinying/dmp#5]
Thanks for the nice work.
I have a question about the rank of the LoRA. Have you tested with different LoRA ranks? Will 'larger' LoRAs perform better in any of your experiments?

**Comment by shinying** [comment]
Thanks for your interest. We use a fixed rank size in all the experiments, but you can adjust it [here](https://github.com/shinying/dmp/blob/17fdd6a60d26b05db9df658dfeee8f3312cf0f86/pipeline.py#L135).

**Comment by LIU-Yuxin** [comment]
Thank you
