### ISSUE TITLE
About the label space in semantic segmentation and depth estimation

### ISSUE THREAD

**Issue by Ferry-Li** [shinying/dmp#7]
Thanks for your inspiring work!
In the experiments of semantic segmentation, " The training and inference of the diffusion model are conducted using the color maps (in the RGB space)." and "the predicted color maps are converted to categorical label maps by assigning each pixel to its nearest category in the color space."
In terms of this, how do you calculate the distance between different colors?
And in the depth estimation, will there be some difference between performance when I set the label space as 'RGB' and grayscale?

**Comment by shinying** [comment]
Thanks for you interest.
We calculate Euclidean distance in Lab space, but there is not much difference from RGB space.
For depth estimation, we duplicate grayscale values for three channels, so technically they are the same.
